### ISSUE TITLE
Procmon Install Fails

### ISSUE THREAD

**Issue by mbluett88** [Sysinternals/ProcMon-for-Linux#25]
I issued the set of commands both in #1 and #2. Neither works.
The first fails stating that it is not a DEB package.
The 2nd fails:
sudo apt-get install procmon
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package procmon
** Mint 20.

**Comment by rwperrott** [comment]
I second that, on Mint LMDE 4 (currently Debian 10.2)

- $(lsb_release -rs) part of install URL failed to resolve
- Opened https://packages.microsoft.com/config/ubuntu/ in a web browser
- Clicked on the 19.10 directory link
- Download packages-microsoft-prod.deb
- sudo dpkg -i packages-microsoft-prod.deb ran fine
- sudo apt-get install procmon failed "E: Unable to locate package procmon"

**Comment by spvkgn** [comment]
> E: Unable to locate package procmon

There is no procmon debian package for your ubuntu release yet https://packages.microsoft.com/ubuntu/19.10/prod/pool/main/p/
It packaged for 18.04 lts only https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/p/procmon/

**Comment by mbluett88** [comment]
I realize there is no package yet. What my post was about was the instructions about how to install Procmon from the Github repositories.

**Comment by jahabibi** [comment]
As @spvkgn noted we have only published a package for Ubuntu 18.04 LTS as is noted in our [installation instructions](https://github.com/microsoft/ProcMon-for-Linux/blob/main/INSTALL.md#ubuntu-1804). Due to this when you manually downloaded the `packages-microsoft-prod.deb` from the Microsoft Ubuntu 19.10 repository you registered the Microsoft Ubuntu 19.10 package feed, not the Microsoft Ubuntu 18.04 LTS feed.

To configure your system with the Microsoft Ubuntu 18.04 LTS package feed you would need to do the following:
1. Remove the previous `packages-microsoft-prod.deb`: `sudo apt purge packages-microsoft-prod`
2. Download Ubuntu 18.04 Microsoft feed package: `wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb`
3. Install package feed: `sudo dpkg -i packages-microsoft-prod.deb`
4. Update local package feed: `sudo apt update`
5. Install Procmon: `sudo apt install procmon`

**Comment by joekinley** [comment]
@jahabibi your instructions did not work with focal fossa 20.04. I still get the `E: Unable to locate package procmon`

**Comment by Velocet** [comment]
@joekinley The provided instructions work fine on 19.10 and 20.04. Both WSL2. So it seems you missed \`\`\`sudo apt update\`\`\`?

**Comment by mbluett88** [comment]
Nope. Performed the instructions exactly as described.

**Comment by jahabibi** [comment]
@joekinley at this point in time we do not have a preview release candidate for Ubuntu 20.04. Only Ubuntu 18.04 LTS due to the fact that BCC v0.10.0 does not support the kernel that Ubuntu 20.04 ships with. Please follow #2 for updates as move forward in addressing this issue.

**Comment by jahabibi** [comment]
Ubuntu 20.04 now supported with [Procmon 1.0.1](https://github.com/Sysinternals/ProcMon-for-Linux/tree/1.0.1).
