### ISSUE TITLE
fail after install on wsl2 - std::experimental::filesystem::v1::__cxx11::filesystem_error

### ISSUE THREAD

**Issue by benranck** [Sysinternals/ProcMon-for-Linux#4]
After installing from
https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
Running on wsl2 18.04 I get the following error;
```
~$ sudo procmon
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: No such file or directory [/sys/kernel/debug/tracing/events/syscalls]
Aborted
```

**Comment by leommxj** [comment]
same here

**Comment by ldh0227** [comment]
same here...

```
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: No such file or directory [/sys/kernel/debug/tracing/events/syscalls]
Aborted (core dumped)```

**Comment by dazzag24** [comment]
ditto

**Comment by MarioHewardt** [comment]
Try mounting /sys/kernel/debug.

If that still doesn't work it's most likely due to the fact that WSL2 doesn't come with BPF enabled by default and you will need to build the WSL2 kernel with the right configuration to generate and install the correct modules. Here are the rough instructions on how to get that done:

https://gist.github.com/MarioHewardt/5759641727aae880b29c8f715ba4d30f

**Comment by WSLUser** [comment]
I have a config with this enabled along with a bunch of other optimizations and better defaults: https://github.com/microsoft/WSL2-Linux-Kernel/pull/115 Currently requires kernel 5.7.8 or newer. Follow this guide for compilation: https://wsl.dev/wsl2-kernel-zfs/
