### ISSUE TITLE
Support for WSL2

### ISSUE THREAD

**Issue by msftnadavbh** [Sysinternals/ProcMon-for-Linux#62]
After installation on WSL2 : 

uname -ar
Linux nadavbhp1 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

sudo procmon
_terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: No such file or directory [/sys/kernel/debug/tracing/events/syscalls]
Aborted_

**Comment by marcoshaw** [comment]
I wonder if this is more of a WSL2 issue, then a ProcMon one?
[https://gist.github.com/MarioHewardt/5759641727aae880b29c8f715ba4d30f](https://gist.github.com/MarioHewardt/5759641727aae880b29c8f715ba4d30f)

**Comment by MarioHewardt** [comment]
@marcoshaw  correct. You need to enable eBPF on WSL2 and the gist shows you how to do that. Even with that though, there are currently a few blockers in eBPF itself (mainly some helper APIs being namespace aware) that ends up giving false information in procmon. This has since been fixed but only available in the absolute latest kernels (as far as am I aware).
