### ISSUE TITLE
Doesn't seem to work on ubuntu 21.04

### ISSUE THREAD

**Issue by danielkrajnik** [Sysinternals/ProcMon-for-Linux#77]
running this:
wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

gives this
E: Unable to locate package procmon

on ubuntu 21.04

Says it still can't find procmon after following the installation instruction for the .deb package

**Comment by jahabibi** [comment]
Hey @danielkrajnik at this point in time for the preview of Procmon for Linux we only [officially support Ubuntu 18.04 and 20.04](https://github.com/Sysinternals/ProcMon-for-Linux/blob/main/INSTALL.md#ubuntu-1804--2004). With that there is no package available in the Microsoft package repositories for Ubuntu 21.04 which is why `apt` errors out.

If you would like you can manually install the Ubuntu 20.04 package on 21.04 via wget & dpkg. Those instructions would look like the following:

`wget http://packages.microsoft.com/ubuntu/20.04/prod/pool/main/p/procmon/procmon_1.0.1-339_amd64.deb`
`dpkg -i procmon_1.0.1-339_amd64.deb`

However at this point in time Procmon is untested on Ubuntu 21.04 and unsupported. As we move forward we are working attentively to resolve the dependency issue we have so that we can support more distributions. Please follow #70 for further updates.
